nginx:
  image: "bitnami/nginx"
  ports:
    - "8000:8080"
  links:
    - php
  volumes:
    - ./logs:/opt/bitnami/nginx/logs/
    - ./nginx/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf:ro
    - WORKING_DIR:/app:consistent
php:
  image: "bitnami/php-fpm:7.0"
  ports:
    - "9000:9000"
  volumes:
    - WORKING_DIR:/app
mysql:
  image: mysql:5.7@sha256:b3b2703de646600b008cbb2de36b70b21e51e7e93a7fca450d2b08151658b2dd
  ports:
    - "3306:3306"
  volumes:
    - ./db-data:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
phpmyadmin:
  image: "phpmyadmin/phpmyadmin"
  restart: always
  ports:
    - "8080:80"
  links:
    - mysql:mysql
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: root
    PMA_HOST: mysql
